default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        require_serial: true
        types: [python]
    -   id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false
        require_serial: true
    -   id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        require_serial: true
        types: [python]
    -   id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
